"""Loader for the deterministic Aurora reforecast.

Adapted from `aifs_singlev2.open_aifs_singlev2()` -- same pattern (per-
initialization `init_YYYYMMDDT00.zarr` stores, `start_year`/`end_year`
filename-based filtering, single/deterministic -- no ensemble `"number"`
dimension, matching the `-1` ensemble-member count given for this model).
See `graphcast.py` for the near-identical sibling loader -- these two were
specified together (same years, ensemble-member count, ~weekly cadence,
50-day lead time, mostly-overlapping variable list) and are almost certainly
generated by the same pipeline, just missing precipitation here.

CAVEAT (more so than `aifs_singlev2.py`'s own caveat): this has NOT been run
against the real store, and unlike AIFS-single-v2's `ls`-confirmed filename
pattern, Aurora's real directory listing hasn't been seen at all here.
Everything below is inferred from the one-line spec given for this model
(years 2000-2025, `-1` ensemble members, ~weekly initializations, 50-day
lead time, the variable list below, path
`/net/monsoon/marchakitus/reforecast/forecasts_aurora_e2s`) plus the
assumption that, since this lives under the same
`/net/monsoon/marchakitus/reforecast/` parent as AIFS-single-v2's own store,
it follows the same `init_YYYYMMDDT00.zarr`-per-initialization, 6-hourly-step
convention. Confirm against the real store before trusting any of this.

**No `total_precipitation`** -- explicitly confirmed ("No Precipitation")
for this model, unlike GraphCast/AIFS. Do not add `"tp"` to `wanted` or
select `total_precipitation`/relative-precipitation-threshold options in a
notebook pointed at this loader; it isn't there.

**No `2m_dewpoint_temperature` either** (only `2t`, 2m temperature -- no
`2d`, same gap as GraphCast) -- wet-bulb temperature (`wetbulb.py`) CANNOT
be computed for Aurora with the variables given.

Variable list given (short names, presumed to match the store's real
internal names): `2t` (2m temperature), `mslp` (mean sea-level pressure),
`q_1000`/`q_850`/`q_925` (specific humidity at 1000/850/925 hPa), `t_1000`/
`t_850`/`t_925` (temperature at 1000/850/925 hPa), `u_200`/`u_50`/`u_850`
and `v_200`/`v_50`/`v_850` (wind components at 200/50/850 hPa), `z_200`/
`z_500`/`z_850` (geopotential at 200/500/850 hPa). Only `2t` is renamed to
match this pipeline's existing `2m_temperature` naming convention -- the
pressure-level fields are left under their native short names.
"""

import re
from pathlib import Path

import xarray as xr
from dask.diagnostics import ProgressBar

# Assumed, not confirmed for this store specifically -- see module docstring.
_INIT_STORE_FILENAME = re.compile(r"^init_(\d{4})(\d{2})(\d{2})T\d{2}\.zarr$")

# Native short variable names assumed present in the store -- no "tp"
# (confirmed no precipitation) and no "2d" (no dewpoint) -- see module
# docstring.
AURORA_VARIABLES = [
    "2t", "mslp",
    "q_1000", "q_850", "q_925",
    "t_1000", "t_850", "t_925",
    "u_200", "u_50", "u_850",
    "v_200", "v_50", "v_850",
    "z_200", "z_500", "z_850",
]

# Only variables with an existing descriptive-name convention elsewhere in
# this pipeline get renamed; everything else keeps its native short name.
_RENAME = {"2t": "2m_temperature", "lat": "latitude", "lon": "longitude"}


def _init_year(path: Path) -> int:
    """Parse the initialization year from an `init_YYYYMMDDT00.zarr` store name.

    Same helper as `aifs_singlev2._init_year`/`graphcast._init_year`,
    duplicated here (not imported) so this module stays self-contained.
    """
    match = _INIT_STORE_FILENAME.match(path.name)
    if not match:
        raise ValueError(
            f"Unrecognized Aurora store filename: {path.name!r} "
            "(expected 'init_YYYYMMDDT00.zarr' -- unconfirmed for this store, see module docstring)"
        )
    return int(match.group(1))


def open_aurora(
    start_year: int | None = None,
    end_year: int | None = None,
    variables: list[str] | None = None,
) -> xr.Dataset:
    """Open the deterministic Aurora reforecast (2000-2025, no ensemble dimension, no precipitation).

    Parameters
    ----------
    start_year, end_year : int, optional
        If given, only initializations with `start_year <= year <= end_year`
        are opened (each bound independently optional). Parsed from each
        store's filename *before* calling `xr.open_mfdataset`, avoiding
        opening zarr metadata for stores outside the requested range --
        same approach as `aifs_singlev2.open_aifs_singlev2`. Omit both to
        open every available initialization.
    variables : list of str, optional
        Which raw short variable names (from `AURORA_VARIABLES`) to actually
        load -- e.g. `["2t"]` if a caller only needs 2m temperature, rather
        than paying the IO cost of all 17 variables (12 of them
        pressure-level fields this pipeline doesn't otherwise use). Defaults
        to `AURORA_VARIABLES` (everything) if omitted.

    See this module's docstring for the (substantial) caveats: this has not
    been run against, or even had its directory listing seen against, the
    real store, and it has no `total_precipitation`/`2m_dewpoint_temperature`
    at all.
    """
    root = Path("/net/monsoon/marchakitus/reforecast/forecasts_aurora_e2s")
    paths = sorted(root.glob("*.zarr"))
    for path in paths:
        assert path.is_dir(), f"{path} does not exist?"

    if start_year is not None or end_year is not None:
        paths = [
            path
            for path in paths
            if (start_year is None or _init_year(path) >= start_year)
            and (end_year is None or _init_year(path) <= end_year)
        ]
        if not paths:
            raise FileNotFoundError(
                f"No Aurora initialization stores found under {root} "
                f"for start_year={start_year}, end_year={end_year}"
            )

    wanted = AURORA_VARIABLES if variables is None else variables

    with ProgressBar():
        ds = xr.open_mfdataset(
            paths,
            engine="zarr",
            combine="nested",
            concat_dim="time",
            preprocess=lambda x: x[wanted],
            chunks={
                "time": 1,  # unavoidable: one time per store
                "prediction_timedelta": 24,  # assumed 6-hourly steps, unconfirmed -- see module docstring
                "latitude": 180,
                "longitude": 180,
            },
            parallel=True,
            data_vars="all",
            coords="minimal",
            compat="override",
            join="override",
            combine_attrs="override",
            consolidated=None,
        )
    # Only rename keys actually present -- xr.Dataset.rename() raises if
    # asked to rename something that doesn't exist (relevant if a caller
    # restricts variables= to something narrower than AURORA_VARIABLES).
    rename_map = {name: renamed for name, renamed in _RENAME.items() if name in ds.variables}
    return ds.rename(rename_map)
